export const book_data = [
  {
    id: 1,
    imgUrl: "https://i.ibb.co/7pFCC2Z/18.png",
    author: "https://i.ibb.co/BtL3HDL/4.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 2,
    imgUrl: "https://i.ibb.co/L5MwSKK/17.png",
    author: "https://i.ibb.co/rdF8yw3/2.png",
    new: false,
    reading: false,
    finished: true,
  },
  {
    id: 3,
    imgUrl: "https://i.ibb.co/g3FS11t/16.png",
    author: "https://i.ibb.co/wsTTvdJ/3.png",
    new: false,
    reading: true,
    finished: false,
  },
  {
    id: 4,
    imgUrl: "https://i.ibb.co/Wz8FbLg/15.png",
    author: "https://i.ibb.co/k3nTz0L/1.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 5,
    imgUrl: "https://i.ibb.co/Db0rZgd/14.png",
    author: "https://i.ibb.co/BtL3HDL/4.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 6,
    imgUrl: "https://i.ibb.co/ZfH56zQ/13.png",
    author: "https://i.ibb.co/rdF8yw3/2.png",
    new: false,
    reading: true,
    finished: false,
  },
  {
    id: 7,
    imgUrl: "https://i.ibb.co/8DfZL8J/11.png",
    author: "https://i.ibb.co/wsTTvdJ/3.png",
    new: false,
    reading: false,
    finished: true,
  },
  {
    id: 8,
    imgUrl: "https://i.ibb.co/c6Fc3ML/12.png",
    author: "https://i.ibb.co/k3nTz0L/1.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 9,
    imgUrl: "https://i.ibb.co/WpGDnVP/10.png",
    author: "https://i.ibb.co/BtL3HDL/4.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 10,
    imgUrl: "https://i.ibb.co/7tWsy3r/9.png",
    author: "https://i.ibb.co/rdF8yw3/2.png",
    new: false,
    reading: true,
    finished: false,
  },
  {
    id: 11,
    imgUrl: "https://i.ibb.co/LNvwZ0Z/8.png",
    author: "https://i.ibb.co/wsTTvdJ/3.png",
    new: false,
    reading: false,
    finished: true,
  },
  {
    id: 12,
    imgUrl: "https://i.ibb.co/kHxH3GN/7.png",
    author: "https://i.ibb.co/k3nTz0L/1.png",
    new: false,
    reading: false,
    finished: true,
  },
  {
    id: 13,
    imgUrl: "https://i.ibb.co/y8g8yhQ/6.png",
    author: "https://i.ibb.co/BtL3HDL/4.png",
    new: false,
    reading: false,
    finished: true,
  },
  {
    id: 14,
    imgUrl: "https://i.ibb.co/2d925w3/5.png",
    author: "https://i.ibb.co/rdF8yw3/2.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 15,
    imgUrl: "https://i.ibb.co/PD28DZx/4.png",
    author: "https://i.ibb.co/wsTTvdJ/3.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 16,
    imgUrl: "https://i.ibb.co/j3zyzCh/3.png",
    author: "https://i.ibb.co/k3nTz0L/1.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 17,
    imgUrl: "https://i.ibb.co/W0QndKC/1.png",
    author: "https://i.ibb.co/BtL3HDL/4.png",
    new: false,
    reading: true,
    finished: false,
  },
  {
    id: 18,
    imgUrl: "https://i.ibb.co/5RgS3HB/21.png",
    author: "https://i.ibb.co/rdF8yw3/2.png",
    new: false,
    reading: false,
    finished: true,
  },
  {
    id: 19,
    imgUrl: "https://i.ibb.co/j6nW3x0/20.png",
    author: "https://i.ibb.co/wsTTvdJ/3.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 20,
    imgUrl: "https://i.ibb.co/7CG2qf4/2.png",
    author: "https://i.ibb.co/k3nTz0L/1.png",
    new: true,
    reading: false,
    finished: false,
  },
  {
    id: 21,
    imgUrl: "https://i.ibb.co/6gLxV1p/19.png",
    author: "https://i.ibb.co/rdF8yw3/2.png",
    new: false,
    reading: true,
    finished: false,
  },
];
